/**
 * Migration 015: Add party_concept column to dm_mode_parties
 *
 * The party_concept (why 4 characters are together) is generated by Opus
 * but was not being persisted. This adds the column so it can be stored
 * and displayed in the Lore panel.
 */

export async function up(db) {
  try {
    await db.execute("ALTER TABLE dm_mode_parties ADD COLUMN party_concept TEXT");
  } catch (e) {
    if (!e.message?.includes('duplicate column')) throw e;
  }
}

export async function down(db) {
  // SQLite doesn't support DROP COLUMN in older versions — leave column in place
}
